### ISSUE TITLE
Merge Testing Base into Primary Main Branch

### ISSUE THREAD

**Issue by VVSBasanth** [StellaX-Technologies/gaac-site#22]
Hey @IbrahimDev00 , 

I've been working on the testing branch, and it looks pretty stable. I believe it's ready to be merged into the "primary-main" branch. This merge will incorporate all the latest changes and ensure that our main branch is up to date with the latest developments. Could you please review and merge it at your earliest convenience? Thanks!

**Comment by IbrahimDev00** [comment]
Hi @VVSBasanth ,
Ive reviewed it and ive found issues with :
1) The navbar, the hamburger menu doesn't open up smoothly on clicking it.
2) The event carousel's arrows don't seem to be fixed but vary with the content in the box.

Since you're working on the landing page, could you also look into it?
Ill try my fixes as well.

**Comment by Nomadic-Nex** [comment]
NA
